name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      

      - name: Make dragon.sh executable
        run: wsl -d Ubuntu "chmod +x /mnt/c/Users/ibrah/Desktop/Sprints-Devops/Week-5/second/actions-runner/_work/Self-Hosted-Runner-Cowsay/Self-Hosted-Runner-Cowsay/dragon.sh"
        shell: powershell

      - name: Run Dragon Script
        run: wsl -d Ubuntu "/mnt/c/Users/ibrah/Desktop/Sprints-Devops/Week-5/second/actions-runner/_work/Self-Hosted-Runner-Cowsay/Self-Hosted-Runner-Cowsay/dragon.sh"
        shell: powershell
