name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run dragon script
        run: |
          # Convert path and fix line endings
          $wslPath = "${{ github.workspace }}".Replace('\', '/').Replace('C:', '/mnt/c')
          wsl -d Ubuntu bash -c "
            # Convert Windows line endings to Unix
            sed -i 's/\r$//' '$wslPath/dragon.sh'
            chmod +x '$wslPath/dragon.sh'
            '$wslPath/dragon.sh'
          "
        shell: powershell