name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Make dragon.sh executable
        run: wsl -d Ubuntu chmod +x ./dragon.sh
        shell: powershell
        
      - name: Run Dragon Script in WSL
        run: wsl -d Ubuntu ./dragon.sh

        shell: powershell

