name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      
      - name: Convert line endings
        run: |
          $filePath = "${{ github.workspace }}/dragon.sh"
          (Get-Content $filePath -Raw).Replace("`r`n","`n") | Set-Content $filePath -NoNewline

      - name: Run dragon script with output
        run: |
          $wslPath = "${{ github.workspace }}".Replace('\', '/').Replace('C:', '/mnt/c')
          $output = wsl -d Ubuntu bash -c "chmod +x '$wslPath/dragon.sh' && '$wslPath/dragon.sh'"
          Write-Output "Script output:"
          Write-Output $output
        shell: powershell