name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

            
      - name: Run dragon script
        run: |
          $wslPath = "${{ github.workspace }}".Replace('\', '/').Replace('C:', '/mnt/c')
          $command = @"
          chmod +x '$wslPath/dragon.sh'
          '$wslPath/dragon.sh'
          "@
          wsl -d Ubuntu bash -c "$command"
        shell: powershell