name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dragon 
        run: ./dragon.ps1