name: Dragon CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  ASCII-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      

      - name: Make dragon.sh executable and run it
        run: |
          wsl -d Ubuntu bash -c "chmod +x ~/$(basename '${{ github.workspace }}')/dragon.sh && ~/$(basename '${{ github.workspace }}')/dragon.sh"
        shell: powershell
